### PR TITLE
Puppet-Maint does not work with puppet >= 4.0

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Comment by liamjbennett** [comment]
Thanks for testing this. What problem(s) did you find with Puppet 4?

**Comment by roidelapluie** [comment]
nitrogen  ~/work/inuits/puppetmaster $ rake maint:unused_code
---> maint:unused_code
rake aborted!
uninitialized constant Puppet::Parser::Lexer

Tasks: TOP => maint:unused_code
(See full trace by running task with --trace)

**Comment by roidelapluie** [comment]
$ rake maint:unused_code
---> maint:unused_code
rake aborted!
uninitialized constant Puppet::Parser::Lexer

Tasks: TOP => maint:unused_code
(See full trace by running task with --trace)

**Comment by liamjbennett** [comment]
Ok, I should be able to fix that soon. It appears that class has been replaced with `Puppet::Pops::Parser::Lexer2`

**Pull request closed without merging**
